p4/flask_app/posts/routes.py
import base64, io
from flask import Blueprint, render_template, url_for, redirect, request, flash, current_app
from flask_login import current_user, login_required
from mongoengine.queryset.visitor import Q

from .. import post_client
from ..forms import PostForm, CommentForm, SearchForm
from ..models import User, Post, Comment
from ..utils import current_time
from flask import send_file


posts = Blueprint("posts", __name__)  # Make sure this is "posts" not "movies"

def get_b64_img(username):
    user = User.objects(username=username).first()
    if user and user.profile_pic:
        try:
            bytes_im = io.BytesIO(user.profile_pic.read())
            image = base64.b64encode(bytes_im.getvalue()).decode()
            return image
        except:
            return None
    return None

def get_b64_img_post(post_id):
    """Return base64 encoded image for a post"""
    try:
        post = Post.objects.get(id=post_id)
        if post and post.image:
            bytes_im = io.BytesIO(post.image.read())
            image = base64.b64encode(bytes_im.getvalue()).decode()
            return image
    except:
        pass
    return None


@posts.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for("posts.query_results", query=form.search_query.data))
    
    # Get recent posts for the feed
    recent_posts = post_client.get_recent_posts(20)
    
    return render_template("index.html", form=form, posts=recent_posts)

@posts.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = post_client.search(query)
        return render_template("query.html", results=results, query=query)
    except ValueError as e:
        return render_template("query.html", error_msg=str(e), query=query)

@posts.route("/create-post", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        # Create a new post
        new_post = Post(
            author=current_user._get_current_object(),
            content=form.content.data,
            category=form.category.data,
            date=current_time()
        )
        
        # Handle image upload if provided
        if form.image.data:
            new_post.image.put(form.image.data, content_type=form.image.data.content_type)
        
        new_post.save()
        flash("Post created successfully!", "success")
        return redirect(url_for("posts.index"))
    
    return render_template("userPost.html", form=form)

@posts.route("/post/<post_id>", methods=["GET", "POST"])
def post_detail(post_id):
    try:
        post = post_client.retrieve_post_by_id(post_id)
    except ValueError as e:
        flash(str(e), "error")
        return redirect(url_for("posts.index"))
    
    # Handle commenting
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(
            post=post,
            commenter=current_user._get_current_object(),
            content=form.content.data,
            date=current_time()
        )
        comment.save()
        return redirect(url_for("posts.post_detail", post_id=post_id))
    
    # Fetch comments for this post
    comments = Comment.objects(post=post)
    
    # Get author's profile pic
    author_pic = get_b64_img(post.author.username)
    
    return render_template(
        "post_detail.html", 
        form=form, 
        post=post, 
        comments=comments, 
        author_pic=author_pic
    )

@posts.route("/post/<post_id>/image")
def serve_image(post_id):
    post = Post.objects.get_or_404(id=post_id)

    if post.image:
        return send_file(
            io.BytesIO(post.image.read()),
            mimetype=post.image.content_type
        )
    else:
        return "No image found", 404


@posts.route("/category/<category>")
def category_posts(category):
    posts = post_client.get_posts_by_category(category)
    return render_template(
        "category.html", 
        posts=posts, 
        category=category,
        get_b64_img=get_b64_img,  # The existing function for user profile pics
        get_b64_img_post=get_b64_img_post  # Add this line
    )

@posts.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    
    if not user:
        return render_template("user_detail.html", error="User not found.")
    
    reviews = post_client.get_user_posts(user)  # renamed from 'posts'
    image = get_b64_img(username)
    
    return render_template(
        "user_detail.html", 
        current_user=user,         # renamed from 'user'
        reviews=reviews,           # renamed from 'posts'
        image=image,
        error=None
    )

p4/flask_app/users/routes.py
import io
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User
from flask_dance.consumer import oauth_authorized
from flask import current_app

users = Blueprint("users", __name__)

""" ************ User Management views ************ """
# login and register do nothing here for right now


@users.route("/google-login")
def google_login():
    # Get the blueprint from the app context
    google_bp = current_app.blueprints.get('google')
    
    if not google_bp.session.authorized:
        return redirect(url_for("google.login"))
    
    # Use the blueprint's session
    resp = google_bp.session.get("/oauth2/v1/userinfo")
    if not resp.ok:
        return "Failed to fetch user info", 403
    
    user_info = resp.json()
    google_id = user_info["id"]
    email = user_info["email"]
    
    # Find or create user
    user = User.objects(google_id=google_id).first()
    if not user:
        user = User.objects(email=email).first()
        if user:
            # Merge existing account with Google login
            user.google_id = google_id
            user.save()
        else:
            # Generate unique username
            base_username = user_info["email"].split("@")[0]
            unique_username = base_username
            counter = 1
            
            # Check for existing username and increment counter if needed
            while User.objects(username=unique_username).first():
                unique_username = f"{base_username}{counter}"
                counter += 1
            
            # Create new user with guaranteed unique username
            user = User(
                username=unique_username,
                email=email,
                google_id=google_id,
                password=None
            )
            user.save()
    
    login_user(user)
    return redirect(url_for("posts.index"))

@oauth_authorized.connect
def google_logged_in(blueprint, token):
    # Only handle Google blueprint events
    if blueprint.name != "google":
        return
    
    # Get fresh user info from Google
    resp = blueprint.session.get("/oauth2/v1/userinfo")
    if not resp.ok:
        return
    
    user_info = resp.json()
    google_id = user_info["id"]
    
    # Find user and update token
    user = User.objects(google_id=google_id).first()
    if user:
        user.google_token = token["access_token"]
        user.save()

# TODO: implement
@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("posts.index"))
    
    registration_form = RegistrationForm()

    if registration_form.validate_on_submit():
        username = registration_form.username.data
        email = registration_form.email.data
        password = registration_form.password.data

        hashed_password = bcrypt.generate_password_hash(password)
        user = User(username=username, email=email, password=hashed_password, profile_pic=None)
        user.save()
        flash("Account created successfully!", "success")
        return redirect(url_for("users.login"))
    
    error_msg = None
    if request.method == "POST" and not registration_form.validate():
        error_msg = "Registration was not successful"

    return render_template("register.html", form=registration_form, error_msg=error_msg)


# TODO: implement
@users.route("/login", methods=["GET", "POST"])
def login():

    if current_user.is_authenticated:
        return redirect(url_for("posts.index")) 
    
    login_form = LoginForm()
    
    if login_form.validate_on_submit():
        user = User.objects(username=login_form.username.data).first()

        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            
            login_user(user)
            flash('Login successful!', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('Login unsuccessful. Please check username and password', 'danger')

    return render_template("login.html", form=login_form)

# TODO: implement
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("posts.index"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():

    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
   
    # TODO: handle update username form submit
    if update_username_form.submit_username.data and update_username_form.validate(): 
        
        new_username = update_username_form.username.data
        current_user.modify(username=new_username)
        current_user.save()
        flash("Username updated successfully!", "success")
        return redirect(url_for("users.account"))   
        
    
    # TODO: handle update profile pic form submit
    if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
        img = update_profile_pic_form.picture.data
        filename = secure_filename(img.filename)
        content_type = img.content_type  # safer than inferring from extension

        if current_user.profile_pic.get() is None:
            current_user.profile_pic.put(img.stream, content_type=content_type, filename=filename)
        else:
            current_user.profile_pic.replace(img.stream, content_type=content_type, filename=filename)

        current_user.save()
        flash("Image updated successfully!", "success")
        return redirect(url_for("users.account"))   

        
    image = None
    if current_user.profile_pic:
        try:
            bytes_io = io.BytesIO(current_user.profile_pic.read())
            image = base64.b64encode(bytes_io.getvalue()).decode()
        except Exception as e:
            print(f"Error reading profile_pic: {e}")
            pass

    return render_template(
        "account.html",
        update_username_form=update_username_form,
        update_profile_pic_form=update_profile_pic_form,
        image=image,
        error="update account was not successful"
    )

p4/flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% if image %}
        {# Profile picture #}
        <img class="rounded-2xl h-24 w-24" src="data:image/png;base64,{{image}}" alt="image">
    {% endif %}

    {# TODO: Greeting (must include the current user's username) #}
    <!-- we must greet but what is the current user value_name? -->
    <h2 class="text-2xl">Hello, {{ current_user.username }}!</h2>

</div>

<!-- note so were given the forms to update
    both usernanme and profile picture
    we must go into forms.py and create
    two new forms for each of these   
    # note if picture doeesn't exist ass profile picture
    # 2 if a picture already exist just replace it in the db 
    # then disply users current prfile picture
    #  Add a link to view all of the user's reviews -> user_detail(username)

    # Read the templates to see what arguments to pass in when calling render_template()
-->

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Username
    </h3>
    <form class="review-form" method="POST" action="">
        {{ update_username_form.csrf_token }}
        <div class="form-group">
            {{ update_username_form.username.label }}
            {{ update_username_form.username(class="form-content") }}
            {% if update_username_form.username.errors %}
            <div class="error" role="alert">
                {% for error in update_username_form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_username_form.submit_username(class="review-button") }}
    </form>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Profile Picture
    </h3>
    <form class="review-form" method="POST" action="" enctype="multipart/form-data">
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture.label }}
            {{ update_profile_pic_form.picture(class="form-content") }}
            {% if update_profile_pic_form.picture.errors %}
            <div class="error" role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture(class="review-button") }}
    </form>
</div>

<div class="flex justify-center">
    {# TODO: Link to see all of the current user's reviews. #}
    <a href="{{ url_for('posts.user_detail', username=current_user.username) }}">
        View My Posts
      </a>
      
</div>
{% endblock %}

p4/flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='compiled.css')}}"
    />
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>WeConnect</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
</body>
</html>

p4/flask_app/templates/category.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold text-center mb-8 text-white capitalize">{{ category }} Posts</h1>
  
  <!-- Category navigation -->
  <div class="flex justify-center gap-8 mb-12">
    <a href="{{ url_for('posts.category_posts', category='sports') }}" 
       class="my-5 navlink {% if category == 'sports' %}!bg-blue-500 text-white{% else %}bg-gray-800 hover:bg-gray-700 text-white{% endif %} px-6 py-3 rounded-full">
      Sports
    </a>
    <a href="{{ url_for('posts.category_posts', category='news') }}" 
       class="my-5 navlink {% if category == 'news' %}!bg-green-500 text-white{% else %}bg-gray-800 hover:bg-gray-700 text-white{% endif %} px-6 py-3 rounded-full">
      News
    </a>
    <a href="{{ url_for('posts.category_posts', category='entertainment') }}" 
       class="my-5 navlink {% if category == 'entertainment' %}!bg-purple-500 text-white{% else %}bg-gray-800 hover:bg-gray-700 text-white{% endif %} px-6 py-3 rounded-full">
      Entertainment
    </a>
  </div>
  
  <!-- Posts in this category -->
    {% if posts %}
    <div class="container mx-auto w-full md:w-2/3 lg:w-1/2">
      {% for post in posts %}
        <div class="bg-gray-800 rounded-lg shadow-lg overflow-hidden mb-6">
          <div class="p-6">
            <!-- Post header with author info -->
            <div class="flex items-center mb-4">
              <!-- Default avatar always shown -->
              <div class="rounded-full h-4 w-4 bg-gray-600 flex items-center justify-center text-white text-lg font-bold mr-3">
                {{ post.author.username[0]|upper }}
              </div>
                
              <div>
                <a href="{{ url_for('posts.user_detail', username=post.author.username) }}" class="font-medium text-blue-400 hover:text-blue-300">
                  @{{ post.author.username }}
                </a>
                <div class="text-gray-400 text-sm">{{ post.date }}</div>
              </div>
            </div>
            
            <!-- Post content -->
            <p class="text-gray-200 mb-4">{{ post.content }}</p>
            
            <!-- Post image if available -->
            {% if post.image %}
              <div class="mb-4 rounded-lg overflow-hidden">
                <img src="data:image/png;base64,{{ get_b64_img_post(post.id) }}" class="w-full object-cover" alt="Post image">
              </div>
            {% endif %}
            
            <!-- Post footer with actions -->
            <div class="flex items-center justify-between pt-2 border-t border-gray-700">
              <a href="{{ url_for('posts.post_detail', post_id=post.id) }}" class="text-blue-400 hover:text-blue-300 text-sm flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg>
                View details
              </a>
              
              <!-- Like count would go here -->
              <span class="text-gray-400 text-sm">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 inline-block mr-1" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                </svg>
                {{ post.likes|default(0, true) }}
              </span>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <div class="text-center py-12">
      <div class="bg-gray-800 inline-block rounded-lg px-8 py-6 shadow-lg">
        <p class="text-lg text-gray-300 mb-4">No posts found in the {{ category }} category.</p>
        {% if current_user.is_authenticated %}
          <a href="{{ url_for('posts.create_post') }}" class="inline-block px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600">
            Be the first to post
          </a>
        {% else %}
          <a href="{{ url_for('users.login') }}" class="inline-block px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600">
            Log in to create a post
          </a>
        {% endif %}
      </div>
    </div>
  {% endif %}
  
  <div class="mt-8 text-center">
    <a href="{{ url_for('posts.index') }}" class="text-blue-400 hover:text-blue-300">
      ← Back to Home
    </a>
  </div>
</div>
{% endblock %}

p4/flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between z-40">
    <a class="m-5 navlink" href="{{ url_for('posts.index') }}">
        <!-- make our first span tag to be our search for post -->
        <span class="hidden sm:block">Home</span>
        <span class="block sm:hidden">Home</span>
    </a>
    {% if current_user.is_authenticated %}
    <div class="flex">
    <!-- button that sends to the post page  -->
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('posts.create_post') }}">Post</a>        
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.account') }}">Account</a>
        <a class="my-5 mr-5 ml-0 navlink !bg-red-400/20 hover:!bg-red-500/50 !text-red-400 hover:!text-red-300" href="{{ url_for('users.logout') }}">Logout</a>
    </div>
    {% else %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.register') }}">Register</a>
    </div>
    {% endif %}
</nav>
{% block content %}{% endblock %}{% endblock %}

p4/flask_app/templates/index.html
{% extends "header.html" %} 
{% block content %}
<div class="main-container">
  <div class="decoration-main-container"><div class="decoration-main"></div></div>
  <h2 class="main-title">Discover Posts by Category</h2>

  <!-- Category buttons with styling similar to Login/Register -->
  <div class="flex justify-center my-8 gap-8">
    <a href="{{ url_for('posts.category_posts', category='sports') }}" 
       class="my-5 mr-5 ml-0 navlink bg-gray-800 hover:bg-gray-700 text-white px-6 py-3 rounded-full">
      Sports
    </a>
    <a href="{{ url_for('posts.category_posts', category='news') }}" 
       class="my-5 mr-5 ml-0 navlink bg-gray-800 hover:bg-gray-700 text-white px-6 py-3 rounded-full">
      News
    </a>
    <a href="{{ url_for('posts.category_posts', category='entertainment') }}" 
       class="my-5 mr-5 ml-0 navlink bg-gray-800 hover:bg-gray-700 text-white px-6 py-3 rounded-full">
      Entertainment
    </a>
  </div>
</div>
{% endblock %}

p4/flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.register') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="error" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

    <!-- Add Google Login Button -->
    <div class="mt-6">
        <div class="relative">
            <div class="absolute inset-0 flex items-center">
                <div class="w-full border-t border-gray-300"></div>
            </div>
            <div class="relative flex justify-center text-sm">
                <span class="px-2 bg-white text-gray-500">Or continue with</span>
            </div>
        </div>

        <div class="mt-6">
            <a href="{{ url_for('google.login') }}" class="w-full inline-flex justify-center items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm bg-white text-sm font-medium text-gray-700 hover:bg-gray-50">
                <svg class="w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                    <path fill="#EA4335" d="M12 10v4.8h6.8c-.3 1.5-1.1 2.8-2.4 3.6l3.8 3c2.5-2.4 3.9-5.9 3.9-10 0-3.2-.8-6.2-2.2-8.8l-4.1 3.2c1 2.6 1 5.8-.2 8.2H12z"/>
                    <path fill="#4285F4" d="M5.3 14.7l-1.4 1.1C3.3 13.3 2.5 10.8 2.5 8c0-2.3.6-4.5 1.6-6.4l3.8 3c-.5 1.4-.4 3.1.2 4.4H5.3z"/>
                    <path fill="#FBBC05" d="M16.7 18.4c-1.2.8-2.6 1.3-4.2 1.3-3.2 0-6-2.1-7-5l-4 3.1c1.7 3.3 5.1 5.6 9 5.6 2.7 0 5.2-.7 7.1-2z"/>
                    <path fill="#34A853" d="M12 22c2.7 0 5.2-.9 7.1-2.4l-3.8-3c-1 .7-2.2 1.1-3.6 1.1-2.8 0-5.2-1.9-6-4.5H2.5c1.3 4 5 7 9.5 7z"/>
                    <path fill="#EA4335" d="M12 10h7.8c.1.4.2.8.2 1.3 0 4.3-2.9 7.3-7.2 7.3-2.1 0-4.1-.8-5.5-2.3l-.4-.3-4-3.1-.1-.1H12z"/>
                </svg>
                Sign in with Google
            </a>
        </div>
    </div>
</div>
{% endblock %}

p4/flask_app/templates/post_detail.html
{% extends "header.html" %}
{% block content %}

<div class="container mx-auto px-4 py-8 max-w-4xl">
  {% if error %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4" role="alert">
      <p>{{ error }}</p>
    </div>
  {% endif %}

  <!-- Post Details -->
  <div class="bg-white rounded-lg shadow-lg overflow-hidden mb-8 p-6">
    <div class="flex items-center mb-4">
      {% if author_pic %}
        <img src="data:image/png;base64,{{ author_pic }}" class="w-12 h-12 rounded-full mr-4">
      {% endif %}
      <div>
        <a href="{{ url_for('posts.user_detail', username=post.author.username) }}" class="text-lg font-medium text-blue-600 hover:underline">
          @{{ post.author.username }}
        </a>
        <div class="text-sm text-gray-500">
          {{ post.date }} • {{ post.category|capitalize }}
        </div>
      </div>
    </div>

    <p class="text-gray-800 text-lg mb-6">{{ post.content }}</p>

    {% if post.image %}
      <img src="{{ url_for('posts.serve_image', post_id=post.id) }}" class="w-full max-h-96 object-contain mb-6 rounded">
    {% endif %}
  </div>

  <!-- Comments Section -->
  <div class="bg-white rounded-lg shadow-lg overflow-hidden p-6 mb-8">
    <h3 class="text-xl font-bold mb-6">Comments: ({{ comments|length }})</h3>

    {% if current_user.is_authenticated %}
      <form method="POST" action="" class="mb-6">
        {{ form.csrf_token }}
        <div class="mb-4">
            {{ form.content(
              class="w-full px-3 py-2 border rounded-lg",
              rows=3,
              placeholder="Add a comment...",
              style="color: black; background-color: white;"
          ) }}
            {% if form.content.errors %}
            <div class="text-red-500 text-sm mt-1">
              {% for error in form.content.errors %}
                {{ error }}
              {% endfor %}
            </div>
          {% endif %}
        </div>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
          Post Comment
        </button>
      </form>
    {% else %}
      <p class="text-gray-600 italic">Log in to leave a comment.</p>
    {% endif %}

    {% if comments %}
      {% for comment in comments %}
        <div class="border-b pb-4 mb-4">
          <a href="{{ url_for('posts.user_detail', username=comment.commenter.username) }}" class="text-blue-600 font-semibold hover:underline">
            @{{ comment.commenter.username }}
          </a>
          <p class="text-sm text-gray-500">{{ comment.date }}</p>
          <p class="text-gray-800">{{ comment.content }}</p>
        </div>
      {% endfor %}
    {% else %}
      <p class="text-gray-500 italic">No comments yet. Be the first to comment!</p>
    {% endif %}
  </div>

  <div class="text-center">
    <a href="{{ url_for('posts.index') }}" class="text-blue-500 hover:underline">← Back to Home</a>
  </div>
</div>

{% endblock %}

p4/flask_app/templates/query.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>

<!-- go through our posts that have been created  -->
 <!-- based on the right genre -->

{% endif %}

<div class="results-container">
  <div class="decoration-container"><div class="decoration"></div></div>
  {% for result in results %}
  <a 
    href="{{ url_for('ok.movie_detail', movie_id=result.imdb_id) }}"
    class="group movie-card"
  >
    <img src="{{ result.poster_url }}" class="movie-card-img" alt="missing" />
    <h5 class="movie-card-content"> {{ result.title }}
      <span class="text-neutral-400 font-normal"> &middot; {{ result.year }} </span>
    </h5>
  </a>
  {% endfor %}
</div>

{% endblock %}

p4/flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}

{% if error %}
  <b class="text-red-400" role="alert">
    {{ error }}
  </b>
{% endif %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 mt-8">

  {# User's Profile Picture #}
  {% if image %}
    <div class="flex justify-center mb-4">
      <img class="rounded-full h-24 w-24 object-cover" src="data:image/png;base64,{{ image }}" alt="Profile Picture">
    </div>
  {% endif %}

  {# Indicate whose posts these are #}
  <h2 class="text-2xl font-bold text-center mb-6">{{ current_user.username }}'s Posts</h2>

  {# Show all posts made by the user #}
  {% if reviews %}
    {% for post in reviews %}
      <div class="bg-white p-4 rounded shadow mb-6">
        <p class="text-lg font-semibold text-gray-800">{{ post.content }}</p>
        <p class="text-sm text-gray-500">{{ post.date }}</p>

        {% if post.image %}
          <div class="mt-3">
            <img 
              class="rounded-lg max-h-[300px] mx-auto" 
              src="{{ url_for('posts.serve_image', post_id=post.id) }}" 
              alt="Post Image"
            >
          </div>
        {% endif %}
      </div>
    {% endfor %}
  {% else %}
    <p class="text-center text-gray-500">This user hasn’t created any posts yet.</p>
  {% endif %}

</div>

{% endblock %}